{{- if .Values.admissionWebhooks.enabled -}}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "chart.fullname" . }}-admission
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/inject-ca-from: {{ printf "%s/%s-admission" .Release.Namespace (include "chart.fullname" .) | quote }}
  {{- include "chart.annotations" . | nindent 4 }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "chart.fullname" . }}-webhook
      namespace: {{ .Release.Namespace }}
      path: /mutate-fleetconfig-open-cluster-management-io-v1alpha1-fleetconfig
  failurePolicy: Fail
  name: mfleetconfig-v1alpha1.open-cluster-management.io
  rules:
  - apiGroups:
    - fleetconfig.open-cluster-management.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - fleetconfigs
  sideEffects: None
{{- end }}