---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-fleetconfig-open-cluster-management-io-v1alpha1-fleetconfig
  failurePolicy: Fail
  name: mfleetconfig-v1alpha1.open-cluster-management.io
  rules:
  - apiGroups:
    - fleetconfig.open-cluster-management.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - fleetconfigs
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-fleetconfig-open-cluster-management-io-v1alpha1-fleetconfig
  failurePolicy: Fail
  name: vfleetconfig-v1alpha1.open-cluster-management.io
  rules:
  - apiGroups:
    - fleetconfig.open-cluster-management.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - fleetconfigs
  sideEffects: None
