apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fleetconfig-editor
  labels:
  {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - fleetconfig.open-cluster-management.io
  resources:
  - fleetconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fleetconfig.open-cluster-management.io
  resources:
  - fleetconfigs/status
  verbs:
  - get