name: Planner

on:
  pull_request:
  pull_request_target:
    types: [unlabeled]
  workflow_dispatch:

concurrency:
  group: planner-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    # Skip this job (and subsequently all other planner jobs) if the PR has the `skip-ci` label
    if: |
      ! contains(github.event.pull_request.labels.*.name, 'skip-ci')
    permissions:
      contents: read
      id-token: write
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        fetch-depth: 0
        ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}

    - name: Compute diff refs
      id: compute-refs
      run: |
        set -e

        BASE_SHA=${{ github.event.pull_request.base.sha }}
        HEAD_SHA=${{ github.event.after || github.event.pull_request.head.sha }}

        # Ensure we have both the base and head commits
        git fetch --depth=1 origin $BASE_SHA
        git fetch --depth=1 origin $HEAD_SHA
        echo "BASE_SHA=$BASE_SHA" >> $GITHUB_ENV
        echo "HEAD_SHA=$HEAD_SHA" >> $GITHUB_ENV

        echo "Diff will compare main ($BASE_SHA) with $HEAD_SHA"

    - name: Build changed project matrix
      id: generate
      run: |
        set -e

        matrixJson="{\"repo\":["
        declare -A changedProjects

        for repo in fleetconfig-controller; do
          if git diff --name-only $BASE_SHA $HEAD_SHA | grep "^$repo/"; then
            changedProjects[$repo]=1
          fi
        done

        for repo in "${!changedProjects[@]}"; do
          matrixJson="${matrixJson}\"$repo\","
        done            

        # Remove last "," and add closing brackets
        if [[ $matrixJson == *, ]]; then
          matrixJson="${matrixJson%?}"
        fi
        matrixJson="$matrixJson]}"
        echo "Matrix: $matrixJson"

        # Set outputs
        echo "matrix=$( echo "$matrixJson" )" >> $GITHUB_OUTPUT

        if [[ $matrixJson == "{\"repo\":[]}" ]]; then
          echo "No changes detected for any project"
          echo "matrix=" >> $GITHUB_OUTPUT
        fi

  call-test:
    name: test
    needs: generate-matrix
    if: |
      needs.generate-matrix.outputs.matrix != ''
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    uses: ./.github/workflows/test.yml
    with:
      repo: ${{ matrix.repo }}
    secrets: inherit

  call-e2e:
    name: e2e
    needs: generate-matrix
    if: |
      needs.generate-matrix.outputs.matrix != ''
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    uses: ./.github/workflows/e2e.yml
    with:
      repo: ${{ matrix.repo }}
    secrets: inherit
