---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - fleetconfig.open-cluster-management.io
  resources:
  - hubs
  - spokes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fleetconfig.open-cluster-management.io
  resources:
  - hubs/finalizers
  - spokes/finalizers
  verbs:
  - update
- apiGroups:
  - fleetconfig.open-cluster-management.io
  resources:
  - hubs/status
  - spokes/status
  verbs:
  - get
  - patch
  - update
